### ISSUE TITLE
Video download stopped working today

### ISSUE THREAD

**Issue by anonbergine** [furyutei/twMediaDownloader#116]
Looks like twitter made some changes and the download button under vid tweets no longer works.

**Comment by CinderBH** [comment]
Same here. I get a "Failed to get tweet information !" error when I try.

**Comment by Jitees** [comment]
I was archiving a bot's old posts and got to 38k images and then the extension suddenly died. Hope the fix will be roll out soon.
(I still have [Apr 7, 2019] to [Mar 2, 2015] to archive)

**Comment by storjak** [comment]
Yeah, broken for me too, I can try maybe submitting a PR later if I find some time.
Thanks, elon.
```
main_react.user.js:402 [twMediaDownloader] (2023-07-02T18:49:32.483Z) failed to get tweet_info {tweet_info: null, textStatus: TypeError: Cannot read properties of undefined (reading 'tweets')
    at chrome-extension://cblpjen…, jqXHR: {…}, errorThrown: undefined}errorThrown: undefinedjqXHR: status: 0statusText: ""[[Prototype]]: ObjecttextStatus: TypeError: Cannot read properties of undefined (reading 'tweets')
    at chrome-extension://cblpjenafgeohmnjknfhpdbdljfkndig/js/main_react.user.js:1479:68message: "Cannot read properties of undefined (reading 'tweets')"stack: "TypeError: Cannot read properties of undefined (reading 'tweets')\n    at chrome-extension://cblpjenafgeohmnjknfhpdbdljfkndig/js/main_react.user.js:1479:68"[[Prototype]]: Errortweet_info: null[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
log_error @ main_react.user.js:402
update_video_info @ main_react.user.js:4395
await in update_video_info (async)
download_video @ main_react.user.js:4530
click_handler @ main_react.user.js:4578
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

**Comment by fireattack** [comment]
The api key used to download video (it's actually a twitter's own key for its clients) just got "banned" on server. It always return error code 34 now (see also: #115). Wait until the author find another way.

**Comment by johnjet88** [comment]
Post from the creator. Seems like he's busy https://twitter.com/i/status/1676505010883158016
Fortunately, [TwitterMediaHarvest](https://github.com/EltonChou/TwitterMediaHarvest) still works if anyone needs an alternative for now. Doesn't download in bulk though.

**Comment by ara303** [comment]
I specifically loved that this extension could extract the video URL but not download it. Every other extension I find just downloads videos, but I just want the link to it on twimg.com.

Is anyone aware of any alternative means to do this? Just extracting the link, no download. Any help appreciated. :)

**Comment by nooshstuff** [comment]
> Post from the creator. Seems like he's busy https://twitter.com/i/status/1676505010883158016 Fortunately, [TwitterMediaHarvest](https://github.com/EltonChou/TwitterMediaHarvest) still works if anyone needs an alternative for now. Doesn't download in bulk though.

I don't mind the lack of bulk downloading but one gripe I have with this one is that it download's the video instead of just providing you the direct link to it, which I used to do with this one.

**Comment by CinderBH** [comment]
Welp, I have no idea why but video downloads work again. Maybe Elmo broke it so much he looped all the way back to fixing it.
